name: DDC for tcc
run-name: ${{ github.actor }} is testing out DDC for tcc 🚀
on: workflow_dispatch
jobs:
  DDC:
    strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug output
        run: |
            gcc -v
            gcc --print-file-name=crtbegin.o
            ar V
            echo "kernel: $(uname -r)"
      - name: Setup tcc
        run: ./.github/workflows/scripts/setup.sh
      - name: Perform DDC
        run: ./.github/workflows/scripts/ddc.sh