name: DDC multi-env
run-name: ${{ github.actor }} is testing out DDC in multiple environments 🚀
on: workflow_dispatch
jobs:
  DDC:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug output
        run: |
            which cc 
            ls -la /usr/bin/cc
            ls -la /etc/alternatives/cc
            gcc --print-file-name=crtbegin.o
      - name: Setup env
        run: make deps
      - name: Setup config
        run: |
            ./cproc/configure LDFLAGS=-s --host=x86_64-linux-gnu --target=x86_64-linux-gnu
            mv ./config.h ./cproc/config.h
      - name: Clean up
        run: make clean
      - name: Perform DDC
        run: make
      - name: Self-regeneration comparison
        run: cmp /usr/local/bin/cproc ./stage0/cproc
      - name: DDC comparison
        run: cmp ./stage0/cproc ./stage2/cproc
