name: DDC
run-name: ${{ github.actor }} is testing out DDC 🚀
on: workflow_dispatch
jobs:
  DDC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test GCC
        run: gcc ./hello.c -o hello
      - name: Test standard compiler
        run: |
            which cc 
            ls -la /usr/bin/cc
      - name: Run hello
        run: ./hello
