name: DDC
run-name: ${{ github.actor }} is testing out DDC 🚀
on: workflow_dispatch
jobs:
  DDC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test standard compiler
        run: |
            which cc 
            ls -la /usr/bin/cc
            ls -la /etc/alternatives/cc
            gcc --print-file-name=crtbegin.o
      - name: Setup env
        run: make deps
      - name: Clean up
        run: make clean
      - name: Perform DDC
        run: make
