name: DDC for tcc
run-name: ${{ github.actor }} is testing out DDC for tcc 🚀
on: workflow_dispatch
jobs:
  DDC:
    strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug output
        run: |
            which cc 
            ls -la /usr/bin/cc
            ls -la /etc/alternatives/cc
            gcc --print-file-name=crtbegin.o
      - name: Unpack tcc
        run: tar xvf tinycc-f6385c0.tar.gz
      - name: Configure and install
        run: |
            cd ./tinycc-f6385c0
            ./configure --cc=gcc --extra-ldflags=-s
            make clean
            make
            objcopy -D libtcc.a
            sudo make install
      - name: Perform self-regeneration
        run: |
            cd ./tinycc-f6385c0
            ./configure --cc=tcc --extra-ldflags=-s
            make clean
            make
            objcopy -D libtcc.a
      - name: Rerport hash
        run: sha256sum ./tinycc-f6385c0/tcc ./tinycc-f6385c0/libtcc.a
